apiVersion: apps/v1
kind: Deployment
metadata:
  name: bvk-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bvk-app
  template:
    metadata:
      labels:
        app: bvk-app
    spec:
      containers:
      - name: bvk-nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bvk-apache-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bvk-app
  template:
    metadata:
      labels:
        app: bvk-app
    spec:
      containers:
      - name: bvk-apache-container
        image: httpd:latest
        ports:
        - containerPort: 80
        command: ["httpd-foreground"]
