apiVersion: v1
kind: Service
metadata:
  name: bvk-apache-nginx-service
spec:
  type: ClusterIP          # Change to NodePort or LoadBalancer if needed
  selector:
    app: bvk-app         # Must match nginx deployment label
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80