apiVersion: v1
kind: Service
metadata:
  name: apache-nginx-service
spec:
  selector:
    app: myapp        # Matches both pods
  ports:
  - protocol: TCP
    port: 80          # Service Port
    targetPort: 80    # Pod Port
  type: ClusterIP